# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='credit',
            field=models.CharField(default='', max_length=100),
        ),
    ]
